# Generated by Django 4.2.5 on 2023-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deneme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denemeinteger", models.IntegerField()),
                ("deneme", models.TextField()),
            ],
        ),
    ]
